services:
  - type: web
    name: mysql-hms
    env: docker
    plan: starter
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: Karthi@123
      - key: MYSQL_DATABASE
        value: hms
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: Karthi@123
    ports:
      - 3306
