services:
  - type: web
    name: mysql-hms
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    buildCommand: ./render/build.sh
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: Karthi@123
      - key: MYSQL_DATABASE
        value: hms
    ports:
      - 3306

